// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgK_dxt7s05CRgyYv7WETPUukDDVm5Arg',
    appId: '1:684663003564:web:5470c14f8dc4ec8a840209',
    messagingSenderId: '684663003564',
    projectId: 'cup-tales-b4df2',
    authDomain: 'cup-tales-b4df2.firebaseapp.com',
    storageBucket: 'cup-tales-b4df2.firebasestorage.app',
    measurementId: 'G-HCYTWSC0KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZI6FdWVE7M4CxnlV-LnlvzoLeBsuKMEo',
    appId: '1:684663003564:android:52403f60793896a8840209',
    messagingSenderId: '684663003564',
    projectId: 'cup-tales-b4df2',
    storageBucket: 'cup-tales-b4df2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1IjUxyJc47SFmvV4JnYip9FgVtBv1fiQ',
    appId: '1:684663003564:ios:d5413d8d2b1cd589840209',
    messagingSenderId: '684663003564',
    projectId: 'cup-tales-b4df2',
    storageBucket: 'cup-tales-b4df2.firebasestorage.app',
    androidClientId:
        '684663003564-984dgpmp15anrmrrc4uo2sd8e78d717t.apps.googleusercontent.com',
    iosClientId:
        '684663003564-3a8a4tabuemqu2qfvm3n34bomr1sc405.apps.googleusercontent.com',
    iosBundleId: 'com.cup.tales.cupTales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1IjUxyJc47SFmvV4JnYip9FgVtBv1fiQ',
    appId: '1:684663003564:ios:d5413d8d2b1cd589840209',
    messagingSenderId: '684663003564',
    projectId: 'cup-tales-b4df2',
    storageBucket: 'cup-tales-b4df2.firebasestorage.app',
    androidClientId:
        '684663003564-984dgpmp15anrmrrc4uo2sd8e78d717t.apps.googleusercontent.com',
    iosClientId:
        '684663003564-3a8a4tabuemqu2qfvm3n34bomr1sc405.apps.googleusercontent.com',
    iosBundleId: 'com.cup.tales.cupTales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgK_dxt7s05CRgyYv7WETPUukDDVm5Arg',
    appId: '1:684663003564:web:d058f0aca945263f840209',
    messagingSenderId: '684663003564',
    projectId: 'cup-tales-b4df2',
    authDomain: 'cup-tales-b4df2.firebaseapp.com',
    storageBucket: 'cup-tales-b4df2.firebasestorage.app',
    measurementId: 'G-7QRR5LYESK',
  );
}
